[package]
name = "storagevec"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
hashbrown = { version = "0.8.2", optional = true }
tinymap = "0.2.2"
tinyvec = { version = "0.4.1", features = ["nightly_const_generics"] }

[features]
default = ["alloc"]
alloc = ["hashbrown"]
stack = ["tinyvec/alloc"]
